[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deepcell-imaging"
dynamic = ["version"]

[tool.setuptools]
# Let auto-discovery do its thing.
