name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  # I don't think we need to do this for PRs into main
  # pull_request:
    # branches: ["main"]

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Trigger cloud build
        run: "gcloud builds submit --region=${{ vars.GCP_REGION }} --config=build-batch-container.yaml --substitutions=_GCP_REPOSITORY=${{ vars.GCP_ARTIFACT_REPOSITORY }},_GITHUB_REPOSITORY=${{ github.repository }}."
        working-directory: container

      - name: Push to DockerHub
        if: ${{ vars.DOCKERHUB_REPOSITORY != '' }}
        run: "gcloud builds submit --region=${{ vars.GCP_REGION }} --config=push-dockerhub-container.yaml --substitutions=_DOCKERHUB_REPOSITORY=${{ vars.DOCKERHUB_REPOSITORY }},_GCP_REPOSITORY=${{ vars.GCP_ARTIFACT_REPOSITORY }},_DOCKERHUB_USERNAME_SECRET_NAME=${{ vars.DOCKERHUB_USERNAME_SECRET_NAME }},_DOCKERHUB_PASSWORD_SECRET_NAME=${{ vars.DOCKERHUB_PASSWORD_SECRET_NAME }} ."
        working-directory: container
